M48
; DRILL file {KiCad 7.0.7} date Sun Mar  3 19:12:33 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-03T19:12:33-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C0.1260
%
G90
G05
T1
X2.1464Y-8.8492
X2.1464Y-9.0768
T2
X8.035Y-9.005
X8.035Y-9.085
X8.235Y-9.045
T3
X2.0344Y-9.595
X2.31Y-9.595
T4
X4.2242Y-8.082
X6.6347Y-0.792
X10.2478Y-8.082
X12.6575Y-0.792
T5
X2.054Y-0.794
X14.84Y-0.794
T0
M30
